# For local development only.

version: '3'

services:
  devtools-8.0:
    container_name: devtools-8.0
    hostname: devtools-80
    build: docker/8.0
    working_dir: /srv
    volumes:
      - .:/srv
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    container_name: devtools-mysql
    image: mariadb:10.6.8
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=phalcon
      - MYSQL_DATABASE=phalcon
      - MYSQL_PASSWORD=secret
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    container_name: devtools-postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=phalcon
      - POSTGRES_DB=phalcon
    extra_hosts:
      - "host.docker.internal:host-gateway"
